#importamos la imagen base con pyhton
FROM python:3.12-slim


#creamos carptea de trabajo del contenedor
WORKDIR /app

#Copiamos los requerimientos del servidor 
COPY requirements.txt .

#instalamos los requerimientos 
RUN pip install --no-cache-dir -r requirements.txt

#copiar el codigo del API 
COPY ./app ./app

#exponer el puerto con el que va atrabajar el servidor
EXPOSE 5000

#comando de ejecucion de FASTAPI
CMD ["uvicorn", "app.main:app","--host","0.0.0.0","--port","5000","--reload"]